# Generated by Django 5.0.4 on 2024-04-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_sale_remove_bill_discount_remove_bill_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online')], default='Cash', max_length=10),
        ),
    ]
